### PR TITLE
Changes to make the application easier to set up

### PR DESCRIPTION
**Pull request by 25Pi25**
- Moved source project one folder up and removed the extra executable directory
- Added error handling when no sprites are imported
- Added sprites folder containing a sample sprite by default
- Enabled multiple selections for multiple sprites
- Several small optimizations for class names

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Ok but I have an issue:
On the Control form, the buttons are outside the box. Does it work on your computer?

Also, did you removed the executable folder but didn't changed the readme.

I will approve merging and fix the control form on the master branch (and change the version).

**Comment by ghost** [comment]
But Thanks for the contribution. I didn't expected contribution and fixes from other people this soon.

**Comment by 25Pi25** [comment]
> On the Control form, the buttons are outside the box. Does it work on your computer?

It looks the same as when I worked on it before, here's what it looks like on my setup (though if it looks different on other setups i'd be happy to look into it)
image

> Also, did you removed the executable folder but didn't changed the readme.

that's an oopsie daisies I'll see if I can change that tomorrow too

**Comment by ghost** [comment]
> It looks the same as when I worked on it before, here's what it looks like on my setup (though if it looks different on other setups i'd be happy to look into it)

strange, because this is how your form look on my computer 
image

> I'll see if I can change that tomorrow too

don't worry, unless you have other modification you want to make, i changed the readme and put back the old value for the button position of the control form.

**Pull request merged**
